// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/sinisaos/chi-ent/ent/predicate"
	"github.com/sinisaos/chi-ent/ent/question"
	"github.com/sinisaos/chi-ent/ent/questiontag"
	"github.com/sinisaos/chi-ent/ent/tag"
)

// QuestionTagQuery is the builder for querying QuestionTag entities.
type QuestionTagQuery struct {
	config
	ctx          *QueryContext
	order        []questiontag.OrderOption
	inters       []Interceptor
	predicates   []predicate.QuestionTag
	withQuestion *QuestionQuery
	withTag      *TagQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the QuestionTagQuery builder.
func (qtq *QuestionTagQuery) Where(ps ...predicate.QuestionTag) *QuestionTagQuery {
	qtq.predicates = append(qtq.predicates, ps...)
	return qtq
}

// Limit the number of records to be returned by this query.
func (qtq *QuestionTagQuery) Limit(limit int) *QuestionTagQuery {
	qtq.ctx.Limit = &limit
	return qtq
}

// Offset to start from.
func (qtq *QuestionTagQuery) Offset(offset int) *QuestionTagQuery {
	qtq.ctx.Offset = &offset
	return qtq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (qtq *QuestionTagQuery) Unique(unique bool) *QuestionTagQuery {
	qtq.ctx.Unique = &unique
	return qtq
}

// Order specifies how the records should be ordered.
func (qtq *QuestionTagQuery) Order(o ...questiontag.OrderOption) *QuestionTagQuery {
	qtq.order = append(qtq.order, o...)
	return qtq
}

// QueryQuestion chains the current query on the "question" edge.
func (qtq *QuestionTagQuery) QueryQuestion() *QuestionQuery {
	query := (&QuestionClient{config: qtq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := qtq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := qtq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(questiontag.Table, questiontag.FieldID, selector),
			sqlgraph.To(question.Table, question.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, questiontag.QuestionTable, questiontag.QuestionColumn),
		)
		fromU = sqlgraph.SetNeighbors(qtq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryTag chains the current query on the "tag" edge.
func (qtq *QuestionTagQuery) QueryTag() *TagQuery {
	query := (&TagClient{config: qtq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := qtq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := qtq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(questiontag.Table, questiontag.FieldID, selector),
			sqlgraph.To(tag.Table, tag.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, questiontag.TagTable, questiontag.TagColumn),
		)
		fromU = sqlgraph.SetNeighbors(qtq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first QuestionTag entity from the query.
// Returns a *NotFoundError when no QuestionTag was found.
func (qtq *QuestionTagQuery) First(ctx context.Context) (*QuestionTag, error) {
	nodes, err := qtq.Limit(1).All(setContextOp(ctx, qtq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{questiontag.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (qtq *QuestionTagQuery) FirstX(ctx context.Context) *QuestionTag {
	node, err := qtq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first QuestionTag ID from the query.
// Returns a *NotFoundError when no QuestionTag ID was found.
func (qtq *QuestionTagQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = qtq.Limit(1).IDs(setContextOp(ctx, qtq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{questiontag.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (qtq *QuestionTagQuery) FirstIDX(ctx context.Context) int {
	id, err := qtq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single QuestionTag entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one QuestionTag entity is found.
// Returns a *NotFoundError when no QuestionTag entities are found.
func (qtq *QuestionTagQuery) Only(ctx context.Context) (*QuestionTag, error) {
	nodes, err := qtq.Limit(2).All(setContextOp(ctx, qtq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{questiontag.Label}
	default:
		return nil, &NotSingularError{questiontag.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (qtq *QuestionTagQuery) OnlyX(ctx context.Context) *QuestionTag {
	node, err := qtq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only QuestionTag ID in the query.
// Returns a *NotSingularError when more than one QuestionTag ID is found.
// Returns a *NotFoundError when no entities are found.
func (qtq *QuestionTagQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = qtq.Limit(2).IDs(setContextOp(ctx, qtq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{questiontag.Label}
	default:
		err = &NotSingularError{questiontag.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (qtq *QuestionTagQuery) OnlyIDX(ctx context.Context) int {
	id, err := qtq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of QuestionTags.
func (qtq *QuestionTagQuery) All(ctx context.Context) ([]*QuestionTag, error) {
	ctx = setContextOp(ctx, qtq.ctx, "All")
	if err := qtq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*QuestionTag, *QuestionTagQuery]()
	return withInterceptors[[]*QuestionTag](ctx, qtq, qr, qtq.inters)
}

// AllX is like All, but panics if an error occurs.
func (qtq *QuestionTagQuery) AllX(ctx context.Context) []*QuestionTag {
	nodes, err := qtq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of QuestionTag IDs.
func (qtq *QuestionTagQuery) IDs(ctx context.Context) (ids []int, err error) {
	if qtq.ctx.Unique == nil && qtq.path != nil {
		qtq.Unique(true)
	}
	ctx = setContextOp(ctx, qtq.ctx, "IDs")
	if err = qtq.Select(questiontag.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (qtq *QuestionTagQuery) IDsX(ctx context.Context) []int {
	ids, err := qtq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (qtq *QuestionTagQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, qtq.ctx, "Count")
	if err := qtq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, qtq, querierCount[*QuestionTagQuery](), qtq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (qtq *QuestionTagQuery) CountX(ctx context.Context) int {
	count, err := qtq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (qtq *QuestionTagQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, qtq.ctx, "Exist")
	switch _, err := qtq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (qtq *QuestionTagQuery) ExistX(ctx context.Context) bool {
	exist, err := qtq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the QuestionTagQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (qtq *QuestionTagQuery) Clone() *QuestionTagQuery {
	if qtq == nil {
		return nil
	}
	return &QuestionTagQuery{
		config:       qtq.config,
		ctx:          qtq.ctx.Clone(),
		order:        append([]questiontag.OrderOption{}, qtq.order...),
		inters:       append([]Interceptor{}, qtq.inters...),
		predicates:   append([]predicate.QuestionTag{}, qtq.predicates...),
		withQuestion: qtq.withQuestion.Clone(),
		withTag:      qtq.withTag.Clone(),
		// clone intermediate query.
		sql:  qtq.sql.Clone(),
		path: qtq.path,
	}
}

// WithQuestion tells the query-builder to eager-load the nodes that are connected to
// the "question" edge. The optional arguments are used to configure the query builder of the edge.
func (qtq *QuestionTagQuery) WithQuestion(opts ...func(*QuestionQuery)) *QuestionTagQuery {
	query := (&QuestionClient{config: qtq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	qtq.withQuestion = query
	return qtq
}

// WithTag tells the query-builder to eager-load the nodes that are connected to
// the "tag" edge. The optional arguments are used to configure the query builder of the edge.
func (qtq *QuestionTagQuery) WithTag(opts ...func(*TagQuery)) *QuestionTagQuery {
	query := (&TagClient{config: qtq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	qtq.withTag = query
	return qtq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		QuestionID int `json:"question_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.QuestionTag.Query().
//		GroupBy(questiontag.FieldQuestionID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (qtq *QuestionTagQuery) GroupBy(field string, fields ...string) *QuestionTagGroupBy {
	qtq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &QuestionTagGroupBy{build: qtq}
	grbuild.flds = &qtq.ctx.Fields
	grbuild.label = questiontag.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		QuestionID int `json:"question_id,omitempty"`
//	}
//
//	client.QuestionTag.Query().
//		Select(questiontag.FieldQuestionID).
//		Scan(ctx, &v)
func (qtq *QuestionTagQuery) Select(fields ...string) *QuestionTagSelect {
	qtq.ctx.Fields = append(qtq.ctx.Fields, fields...)
	sbuild := &QuestionTagSelect{QuestionTagQuery: qtq}
	sbuild.label = questiontag.Label
	sbuild.flds, sbuild.scan = &qtq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a QuestionTagSelect configured with the given aggregations.
func (qtq *QuestionTagQuery) Aggregate(fns ...AggregateFunc) *QuestionTagSelect {
	return qtq.Select().Aggregate(fns...)
}

func (qtq *QuestionTagQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range qtq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, qtq); err != nil {
				return err
			}
		}
	}
	for _, f := range qtq.ctx.Fields {
		if !questiontag.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if qtq.path != nil {
		prev, err := qtq.path(ctx)
		if err != nil {
			return err
		}
		qtq.sql = prev
	}
	return nil
}

func (qtq *QuestionTagQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*QuestionTag, error) {
	var (
		nodes       = []*QuestionTag{}
		_spec       = qtq.querySpec()
		loadedTypes = [2]bool{
			qtq.withQuestion != nil,
			qtq.withTag != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*QuestionTag).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &QuestionTag{config: qtq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, qtq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := qtq.withQuestion; query != nil {
		if err := qtq.loadQuestion(ctx, query, nodes, nil,
			func(n *QuestionTag, e *Question) { n.Edges.Question = e }); err != nil {
			return nil, err
		}
	}
	if query := qtq.withTag; query != nil {
		if err := qtq.loadTag(ctx, query, nodes, nil,
			func(n *QuestionTag, e *Tag) { n.Edges.Tag = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (qtq *QuestionTagQuery) loadQuestion(ctx context.Context, query *QuestionQuery, nodes []*QuestionTag, init func(*QuestionTag), assign func(*QuestionTag, *Question)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*QuestionTag)
	for i := range nodes {
		fk := nodes[i].QuestionID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(question.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "question_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (qtq *QuestionTagQuery) loadTag(ctx context.Context, query *TagQuery, nodes []*QuestionTag, init func(*QuestionTag), assign func(*QuestionTag, *Tag)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*QuestionTag)
	for i := range nodes {
		fk := nodes[i].TagID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(tag.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "tag_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (qtq *QuestionTagQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := qtq.querySpec()
	_spec.Node.Columns = qtq.ctx.Fields
	if len(qtq.ctx.Fields) > 0 {
		_spec.Unique = qtq.ctx.Unique != nil && *qtq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, qtq.driver, _spec)
}

func (qtq *QuestionTagQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(questiontag.Table, questiontag.Columns, sqlgraph.NewFieldSpec(questiontag.FieldID, field.TypeInt))
	_spec.From = qtq.sql
	if unique := qtq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if qtq.path != nil {
		_spec.Unique = true
	}
	if fields := qtq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, questiontag.FieldID)
		for i := range fields {
			if fields[i] != questiontag.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if qtq.withQuestion != nil {
			_spec.Node.AddColumnOnce(questiontag.FieldQuestionID)
		}
		if qtq.withTag != nil {
			_spec.Node.AddColumnOnce(questiontag.FieldTagID)
		}
	}
	if ps := qtq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := qtq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := qtq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := qtq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (qtq *QuestionTagQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(qtq.driver.Dialect())
	t1 := builder.Table(questiontag.Table)
	columns := qtq.ctx.Fields
	if len(columns) == 0 {
		columns = questiontag.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if qtq.sql != nil {
		selector = qtq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if qtq.ctx.Unique != nil && *qtq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range qtq.predicates {
		p(selector)
	}
	for _, p := range qtq.order {
		p(selector)
	}
	if offset := qtq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := qtq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// QuestionTagGroupBy is the group-by builder for QuestionTag entities.
type QuestionTagGroupBy struct {
	selector
	build *QuestionTagQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (qtgb *QuestionTagGroupBy) Aggregate(fns ...AggregateFunc) *QuestionTagGroupBy {
	qtgb.fns = append(qtgb.fns, fns...)
	return qtgb
}

// Scan applies the selector query and scans the result into the given value.
func (qtgb *QuestionTagGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, qtgb.build.ctx, "GroupBy")
	if err := qtgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*QuestionTagQuery, *QuestionTagGroupBy](ctx, qtgb.build, qtgb, qtgb.build.inters, v)
}

func (qtgb *QuestionTagGroupBy) sqlScan(ctx context.Context, root *QuestionTagQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(qtgb.fns))
	for _, fn := range qtgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*qtgb.flds)+len(qtgb.fns))
		for _, f := range *qtgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*qtgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := qtgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// QuestionTagSelect is the builder for selecting fields of QuestionTag entities.
type QuestionTagSelect struct {
	*QuestionTagQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (qts *QuestionTagSelect) Aggregate(fns ...AggregateFunc) *QuestionTagSelect {
	qts.fns = append(qts.fns, fns...)
	return qts
}

// Scan applies the selector query and scans the result into the given value.
func (qts *QuestionTagSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, qts.ctx, "Select")
	if err := qts.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*QuestionTagQuery, *QuestionTagSelect](ctx, qts.QuestionTagQuery, qts, qts.inters, v)
}

func (qts *QuestionTagSelect) sqlScan(ctx context.Context, root *QuestionTagQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(qts.fns))
	for _, fn := range qts.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*qts.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := qts.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
